[features]
seeds = false
skip-lint = false

[programs.localnet]
dead_switch = "Fg6PaFpoGXkYsidMpWxTWqkZNVYJz8Nwz9fJf3N4Yf5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
